/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as CompareIdRouteImport } from './routes/compare.$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIdRoute = CompareIdRouteImport.update({
  id: '/compare/$id',
  path: '/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/compare/$id': typeof CompareIdRoute
  '/photo/$id': typeof PhotoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/compare/$id': typeof CompareIdRoute
  '/photo/$id': typeof PhotoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/compare/$id': typeof CompareIdRoute
  '/photo/$id': typeof PhotoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/compare/$id'
    | '/photo/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/compare/$id'
    | '/photo/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/compare/$id'
    | '/photo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CaptureRoute: typeof CaptureRoute
  InsightsRoute: typeof InsightsRoute
  TimelineRoute: typeof TimelineRoute
  CompareIdRoute: typeof CompareIdRoute
  PhotoIdRoute: typeof PhotoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id': {
      id: '/compare/$id'
      path: '/compare/$id'
      fullPath: '/compare/$id'
      preLoaderRoute: typeof CompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CaptureRoute: CaptureRoute,
  InsightsRoute: InsightsRoute,
  TimelineRoute: TimelineRoute,
  CompareIdRoute: CompareIdRoute,
  PhotoIdRoute: PhotoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
