/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoralsIndexRouteImport } from './routes/corals.index'
import { Route as CamerasIndexRouteImport } from './routes/cameras.index'
import { Route as AutomationsIndexRouteImport } from './routes/automations.index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as PhotoIdRouteImport } from './routes/photo.$id'
import { Route as CropIdRouteImport } from './routes/crop.$id'
import { Route as CoralsIdRouteImport } from './routes/corals.$id'
import { Route as CompareIdRouteImport } from './routes/compare.$id'
import { Route as CamerasNewRouteImport } from './routes/cameras.new'
import { Route as CamerasIdRouteImport } from './routes/cameras.$id'
import { Route as AreasIdRouteImport } from './routes/areas.$id'
import { Route as ApiPublicBridgeStepRouteImport } from './routes/api/public/bridge/step'
import { Route as ApiPublicBridgePresetsRouteImport } from './routes/api/public/bridge/presets'
import { Route as ApiPublicBridgeIngestRouteImport } from './routes/api/public/bridge/ingest'
import { Route as ApiPublicBridgeCompareRouteImport } from './routes/api/public/bridge/compare'
import { Route as ApiPublicBridgeClaimRouteImport } from './routes/api/public/bridge/claim'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoralsIndexRoute = CoralsIndexRouteImport.update({
  id: '/corals/',
  path: '/corals/',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIndexRoute = CamerasIndexRouteImport.update({
  id: '/cameras/',
  path: '/cameras/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoIdRoute = PhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CropIdRoute = CropIdRouteImport.update({
  id: '/crop/$id',
  path: '/crop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoralsIdRoute = CoralsIdRouteImport.update({
  id: '/corals/$id',
  path: '/corals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIdRoute = CompareIdRouteImport.update({
  id: '/compare/$id',
  path: '/compare/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasNewRoute = CamerasNewRouteImport.update({
  id: '/cameras/new',
  path: '/cameras/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIdRoute = CamerasIdRouteImport.update({
  id: '/cameras/$id',
  path: '/cameras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIdRoute = AreasIdRouteImport.update({
  id: '/areas/$id',
  path: '/areas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeStepRoute = ApiPublicBridgeStepRouteImport.update({
  id: '/api/public/bridge/step',
  path: '/api/public/bridge/step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgePresetsRoute = ApiPublicBridgePresetsRouteImport.update({
  id: '/api/public/bridge/presets',
  path: '/api/public/bridge/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeIngestRoute = ApiPublicBridgeIngestRouteImport.update({
  id: '/api/public/bridge/ingest',
  path: '/api/public/bridge/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeCompareRoute = ApiPublicBridgeCompareRouteImport.update({
  id: '/api/public/bridge/compare',
  path: '/api/public/bridge/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBridgeClaimRoute = ApiPublicBridgeClaimRouteImport.update({
  id: '/api/public/bridge/claim',
  path: '/api/public/bridge/claim',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/areas/$id': typeof AreasIdRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/cameras/new': typeof CamerasNewRoute
  '/compare/$id': typeof CompareIdRoute
  '/corals/$id': typeof CoralsIdRoute
  '/crop/$id': typeof CropIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/areas/': typeof AreasIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/cameras/': typeof CamerasIndexRoute
  '/corals/': typeof CoralsIndexRoute
  '/api/public/bridge/claim': typeof ApiPublicBridgeClaimRoute
  '/api/public/bridge/compare': typeof ApiPublicBridgeCompareRoute
  '/api/public/bridge/ingest': typeof ApiPublicBridgeIngestRoute
  '/api/public/bridge/presets': typeof ApiPublicBridgePresetsRoute
  '/api/public/bridge/step': typeof ApiPublicBridgeStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/areas/$id': typeof AreasIdRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/cameras/new': typeof CamerasNewRoute
  '/compare/$id': typeof CompareIdRoute
  '/corals/$id': typeof CoralsIdRoute
  '/crop/$id': typeof CropIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/areas': typeof AreasIndexRoute
  '/automations': typeof AutomationsIndexRoute
  '/cameras': typeof CamerasIndexRoute
  '/corals': typeof CoralsIndexRoute
  '/api/public/bridge/claim': typeof ApiPublicBridgeClaimRoute
  '/api/public/bridge/compare': typeof ApiPublicBridgeCompareRoute
  '/api/public/bridge/ingest': typeof ApiPublicBridgeIngestRoute
  '/api/public/bridge/presets': typeof ApiPublicBridgePresetsRoute
  '/api/public/bridge/step': typeof ApiPublicBridgeStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/insights': typeof InsightsRoute
  '/timeline': typeof TimelineRoute
  '/areas/$id': typeof AreasIdRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/cameras/new': typeof CamerasNewRoute
  '/compare/$id': typeof CompareIdRoute
  '/corals/$id': typeof CoralsIdRoute
  '/crop/$id': typeof CropIdRoute
  '/photo/$id': typeof PhotoIdRoute
  '/areas/': typeof AreasIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/cameras/': typeof CamerasIndexRoute
  '/corals/': typeof CoralsIndexRoute
  '/api/public/bridge/claim': typeof ApiPublicBridgeClaimRoute
  '/api/public/bridge/compare': typeof ApiPublicBridgeCompareRoute
  '/api/public/bridge/ingest': typeof ApiPublicBridgeIngestRoute
  '/api/public/bridge/presets': typeof ApiPublicBridgePresetsRoute
  '/api/public/bridge/step': typeof ApiPublicBridgeStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/areas/$id'
    | '/cameras/$id'
    | '/cameras/new'
    | '/compare/$id'
    | '/corals/$id'
    | '/crop/$id'
    | '/photo/$id'
    | '/areas/'
    | '/automations/'
    | '/cameras/'
    | '/corals/'
    | '/api/public/bridge/claim'
    | '/api/public/bridge/compare'
    | '/api/public/bridge/ingest'
    | '/api/public/bridge/presets'
    | '/api/public/bridge/step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/areas/$id'
    | '/cameras/$id'
    | '/cameras/new'
    | '/compare/$id'
    | '/corals/$id'
    | '/crop/$id'
    | '/photo/$id'
    | '/areas'
    | '/automations'
    | '/cameras'
    | '/corals'
    | '/api/public/bridge/claim'
    | '/api/public/bridge/compare'
    | '/api/public/bridge/ingest'
    | '/api/public/bridge/presets'
    | '/api/public/bridge/step'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/capture'
    | '/insights'
    | '/timeline'
    | '/areas/$id'
    | '/cameras/$id'
    | '/cameras/new'
    | '/compare/$id'
    | '/corals/$id'
    | '/crop/$id'
    | '/photo/$id'
    | '/areas/'
    | '/automations/'
    | '/cameras/'
    | '/corals/'
    | '/api/public/bridge/claim'
    | '/api/public/bridge/compare'
    | '/api/public/bridge/ingest'
    | '/api/public/bridge/presets'
    | '/api/public/bridge/step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CaptureRoute: typeof CaptureRoute
  InsightsRoute: typeof InsightsRoute
  TimelineRoute: typeof TimelineRoute
  AreasIdRoute: typeof AreasIdRoute
  CamerasIdRoute: typeof CamerasIdRoute
  CamerasNewRoute: typeof CamerasNewRoute
  CompareIdRoute: typeof CompareIdRoute
  CoralsIdRoute: typeof CoralsIdRoute
  CropIdRoute: typeof CropIdRoute
  PhotoIdRoute: typeof PhotoIdRoute
  AreasIndexRoute: typeof AreasIndexRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  CamerasIndexRoute: typeof CamerasIndexRoute
  CoralsIndexRoute: typeof CoralsIndexRoute
  ApiPublicBridgeClaimRoute: typeof ApiPublicBridgeClaimRoute
  ApiPublicBridgeCompareRoute: typeof ApiPublicBridgeCompareRoute
  ApiPublicBridgeIngestRoute: typeof ApiPublicBridgeIngestRoute
  ApiPublicBridgePresetsRoute: typeof ApiPublicBridgePresetsRoute
  ApiPublicBridgeStepRoute: typeof ApiPublicBridgeStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corals/': {
      id: '/corals/'
      path: '/corals'
      fullPath: '/corals/'
      preLoaderRoute: typeof CoralsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/': {
      id: '/cameras/'
      path: '/cameras'
      fullPath: '/cameras/'
      preLoaderRoute: typeof CamerasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo/$id': {
      id: '/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof PhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$id': {
      id: '/crop/$id'
      path: '/crop/$id'
      fullPath: '/crop/$id'
      preLoaderRoute: typeof CropIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corals/$id': {
      id: '/corals/$id'
      path: '/corals/$id'
      fullPath: '/corals/$id'
      preLoaderRoute: typeof CoralsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$id': {
      id: '/compare/$id'
      path: '/compare/$id'
      fullPath: '/compare/$id'
      preLoaderRoute: typeof CompareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/new': {
      id: '/cameras/new'
      path: '/cameras/new'
      fullPath: '/cameras/new'
      preLoaderRoute: typeof CamerasNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$id': {
      id: '/cameras/$id'
      path: '/cameras/$id'
      fullPath: '/cameras/$id'
      preLoaderRoute: typeof CamerasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$id': {
      id: '/areas/$id'
      path: '/areas/$id'
      fullPath: '/areas/$id'
      preLoaderRoute: typeof AreasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/step': {
      id: '/api/public/bridge/step'
      path: '/api/public/bridge/step'
      fullPath: '/api/public/bridge/step'
      preLoaderRoute: typeof ApiPublicBridgeStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/presets': {
      id: '/api/public/bridge/presets'
      path: '/api/public/bridge/presets'
      fullPath: '/api/public/bridge/presets'
      preLoaderRoute: typeof ApiPublicBridgePresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/ingest': {
      id: '/api/public/bridge/ingest'
      path: '/api/public/bridge/ingest'
      fullPath: '/api/public/bridge/ingest'
      preLoaderRoute: typeof ApiPublicBridgeIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/compare': {
      id: '/api/public/bridge/compare'
      path: '/api/public/bridge/compare'
      fullPath: '/api/public/bridge/compare'
      preLoaderRoute: typeof ApiPublicBridgeCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bridge/claim': {
      id: '/api/public/bridge/claim'
      path: '/api/public/bridge/claim'
      fullPath: '/api/public/bridge/claim'
      preLoaderRoute: typeof ApiPublicBridgeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CaptureRoute: CaptureRoute,
  InsightsRoute: InsightsRoute,
  TimelineRoute: TimelineRoute,
  AreasIdRoute: AreasIdRoute,
  CamerasIdRoute: CamerasIdRoute,
  CamerasNewRoute: CamerasNewRoute,
  CompareIdRoute: CompareIdRoute,
  CoralsIdRoute: CoralsIdRoute,
  CropIdRoute: CropIdRoute,
  PhotoIdRoute: PhotoIdRoute,
  AreasIndexRoute: AreasIndexRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  CamerasIndexRoute: CamerasIndexRoute,
  CoralsIndexRoute: CoralsIndexRoute,
  ApiPublicBridgeClaimRoute: ApiPublicBridgeClaimRoute,
  ApiPublicBridgeCompareRoute: ApiPublicBridgeCompareRoute,
  ApiPublicBridgeIngestRoute: ApiPublicBridgeIngestRoute,
  ApiPublicBridgePresetsRoute: ApiPublicBridgePresetsRoute,
  ApiPublicBridgeStepRoute: ApiPublicBridgeStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
